### ISSUE TITLE
passing through a custom Parser for different Changelog formats.

### ISSUE THREAD

**Issue by jsidney** [RSC-Labs/backstage-changelog-plugin#1]
I have just added this plugin and I am loving the visibility that it provides for our components. However, we are using a different format to "keep a changelog". i see in your docs, you have explained that you can provide a custom parser:
```javascript
export type ChangelogAction = {
    name: string,
    counter: number,
    content: string,
    icon?: any
}

export type ChangelogProps = {
    versionNumber: string,
    actions: ChangelogAction[],
    versionContent: string | undefined
}
```
what I am confused about, is where this property gets passed through to the plugin? would you be able to provide an example of how to do this?

**Comment by radoslaw-sz** [comment]
@jsidney thanks for the comment. I will update README.md to reflect. Let's keep this issue open until done.

**Comment by radoslaw-sz** [comment]
Hi @jsidney ,
I have pushed new README changes related to this topic. Short instruction about creating own parser is here:
https://github.com/RSC-Labs/backstage-changelog-plugin/blob/main/plugins/backstage-changelog-plugin/README.md#how-to-create-my-own-parser
Please kindly check if it clarifies enough or more information is needed.

**Comment by jsidney** [comment]
@radoslaw-sz  - thanks for the update to the README. 
i think the only question that I still have is **where** you would pass through the custom parser? (ie: how would you tell the plugin  to use a custom format?)

**Comment by radoslaw-sz** [comment]
@jsidney  - both ChangelogContent (EntityChangelogContent)  and ChangelogCard (EntityChangelogCard) take optional argument of a type ChangeLogCardProps, which is:
```jsx
/**
 * Props for {@link EntityChangelogCard}.
 *
 * @public
 */
export interface ChangelogCardProps {
    parser?(content: string) : ChangelogProps[]
}
```
so you shall be able to pass there a parser (as a function which takes "string" argument which is the content of Changelog and returns ChangelogProps[]). 
Let me know if it is possible or maybe I missed something - this is my first plugin :)

**Comment by jsidney** [comment]
no problem @radoslaw-sz  - im no expert with Typescript (or React etc) so im also a very slow learner haha!
so just to clarify, if in my `EntityPage.tsx` I have the following:
```javascript
...
<Grid item md={6} xs={12}>
      <EntityChangelogCard />
</Grid>
```
I would have to add something like
```javascript
<EntityChangelogCard ChangelogCardProps =ChangelogProps />
```

**Comment by radoslaw-sz** [comment]
@jsidney no problem, here is the example. 
Let's say you have such changelog:

```md
# Changelog

## [1.1.1] - 2023-03-05

### Added

- Polish translation

### Removed

- Foreign translation
```

You can create separated file called "yourParser.ts", which can have this:
```typescript
import { ChangelogProps } from "@rsc-labs/backstage-changelog-plugin/src/util/types";

export function myParser(changeLogContent: string) : ChangelogProps[] {
    // changeLogContent is content of CHANGELOG file
    // parse that content by mapping it to below structure
    return [
        {
            versionContent: 
                `
                ### Added

                - Polish translation

                ### Removed

                - Foreign translation`
                ,
            versionNumber: "1.0",
            actions: [
                {
                    name: "Added",
                    counter: 1,
                    content: "- Polish translation",
                },
                {
                    name: "Removed",
                    counter: 1,
                    content: "- Foreign translation",
                }
            ]
        }
    ]
}
```

and then use it for example in EntityPage like this:

```jsx
import { myParser } from './yourParser';
...
<Grid item md={6} xs={12}>
      <EntityChangelogCard parser={myParser} />
</Grid>
```

Of course parser itself will be much more complicated because you need properly map your CHANGELOG content to this structure.

**Comment by jsidney** [comment]
Thanks for the detail @radoslaw-sz ! Will go ahead and implement that and see how it works. Once I have it implemented, I'll open a PR with an example :)

**Comment by radoslaw-sz** [comment]
@jsidney Sure! thanks!
Shall we close this issue now?

**Comment by jsidney** [comment]
yeah :) 
thanks again for the help! 👍

**Comment by jsidney** [comment]
@radoslaw-sz  - sorry for re-opening this issue. i am busy writing my custom parser and I have noticed the following error:
![image](https://github.com/RSC-Labs/backstage-changelog-plugin/assets/7551131/a663dfe5-3970-404d-8b8a-e09c7519f5e6)
is this something that is a "bug" or am I just not importing the `ChangelogProps` correctly?

**Comment by radoslaw-sz** [comment]
@jsidney indeed it is a bug, thanks for checking it!
Soon there will be a fix.

**Comment by radoslaw-sz** [comment]
hi @jsidney  - please kindly check the latest release (both frontend and backend packages have been updated). I hope exports have been fixed.

**Comment by jsidney** [comment]
thanks for the update @radoslaw-sz . i am busy updating and testing now, but the error that I mentioned has gone. now I need to make sure that my parser works :)

**Comment by jonathan-s** [comment]
Feels like this bit should go into the documentation. Because that is not clear at all when you're looking at the docs for creating a custom parser. 

```
import { myParser } from './yourParser';
...
<Grid item md={6} xs={12}>
      <EntityChangelogCard parser={myParser} />
</Grid>
```

**Comment by radoslaw-sz** [comment]
@jonathan-s update done. Here is the newest version: https://github.com/RSC-Labs/backstage-changelog-plugin/tree/main/plugins/backstage-changelog-plugin#how-to-create-my-own-parser
