### ISSUE TITLE
Issues found related to the "SEE CHANGES" button feature.

### ISSUE THREAD

**Issue by christian-777** [RSC-Labs/backstage-changelog-plugin#3]
Following the CHANGELOG.md examples on my Backstage application, the first version (0.0.1) or the last in the list doesn't have the "SEE CHANGES" feature. Additionally, when a version has an empty tag (Added, Fixed, Changed, Removed), the "SEE CHANGES" feature doesn't work either.

During my tests, I identified these issues.

**Comment by radoslaw-sz** [comment]
hi @christian-777 - if you will still see this issue, please kindly re-open it. I am closing now.
