### ISSUE TITLE
New Backend System

### ISSUE THREAD

**Issue by imbabamba** [RSC-Labs/backstage-changelog-plugin#5]
Can the plugin be upgraded into using the new backend system?

**Comment by radoslaw-sz** [comment]
hi @imbabamba - I have never migrate any plugin and I am not familiar with the new backend system. Do you know how much work needs to be done here? Is it backward compatible?

**Comment by imbabamba** [comment]
doesn't seem to be that much work.

https://backstage.io/docs/backend-system/building-plugins-and-modules/migrating/

**Comment by radoslaw-sz** [comment]
thanks @imbabamba  - I will check, but as it is now quite low priority for me, I can make this improvement at least in the next week or week after.

**Comment by imbabamba** [comment]
@radoslaw-sz there is no rush. I would be very happy if it would be available with new backend and dependency bump before summer :) We love this little plugin. Good work!

**Comment by radoslaw-sz** [comment]
hi @imbabamba  - please kindly check version 0.4.0 if it works (I hope I have migrated it correctly).

PS. Sorry, it took more than one week or two 😅

**Comment by imbabamba** [comment]
@radoslaw-sz haha no rush, pleased with migration. Awesome work! All seems to work but getting a deprecation warning in the log at startup. 

`changelog warn DEPRECATION WARNING: The 'getPath' option for HttpRouterService is deprecated. The ability to reconfigure the '/api/' path prefix for plugins will be removed in the future. `
