### ISSUE TITLE
Support for Semantic Versioning (SemVer) Notation in Changelog Plugin

### ISSUE THREAD

**Issue by juniorsdj** [RSC-Labs/backstage-changelog-plugin#6]
I've implemented a parser for Semantic Versioning (SemVer) notation in the backstage-changelog-plugin. Currently, the plugin supports the Keep a Changelog format, but I found it necessary to extend its capabilities to accommodate projects that use SemVer-style changelogs.

The SemVer parser extracts version numbers, release dates, and changelog entries in SemVer format, allowing users to generate changelogs in a format compatible with SemVer conventions.

This addition would provide flexibility for projects that adhere to SemVer guidelines and streamline the changelog generation process for such projects.

Please consider integrating this SemVer parser into the backstage-changelog-plugin to enhance its versatility and better serve the needs of the community.

Thank you for considering this enhancement. If you have any questions or require further information, please let me know.

Best regards,
Jennysson Junior

**Comment by radoslaw-sz** [comment]
hi @juniorsdj  - thanks for raising this issue. Unfortunately, I am not able to do any more feature requests in near future. I am focusing on some other projects. Of course, I am always open for pull requests.

**Comment by radoslaw-sz** [comment]
hi @juniorsdj  - your changes are landed in 0.5.0 version. Please check if it works :) and thank you again for your contribution!

**Comment by juniorsdj** [comment]
Thank you @radoslaw-sz, I've checked and works fine. 

It was a pleasure
