### ISSUE TITLE
Do not show card or tab if the a changelog cannot be found 

### ISSUE THREAD

**Issue by nia-potato** [RSC-Labs/backstage-changelog-plugin#9]
Hi @radoslaw-sz , thanks for the great plugin. 

I would like to adopt this plugin within our organization, but i realized not all of our services have changelogs, thus the default behavior of if a changelog does not exists, show 404 on the overview page can create alot of visual noise to the users. 

```
{"response":{},"body":{"error":{"name":"NotFoundError","message":"https://gitlab.domain.com/group/reponame/-/blob/main/CHANGELOG.md could not be read as https://gitlab.domain.com/api/v4/projects/1111/repository/files/CHANGELOG.md/raw?ref=main, 404 Not Found","stack":"NotFoundError: https://gitlab.domain.com/group/reponame/-/blob/main/CHANGELOG.md could not be read as https://gitlab.domain.com/api/v4/projects/1111/repository/files/CHANGELOG.md/raw?ref=main, 404 Not Found\n at _GitlabUrlReader.readUrl (/Users/test/repo/backstage/src/node_modules/@backstage/backend-common/src/reading/GitlabUrlReader.ts:115:13)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at <anonymous> (/Users/test/repo/backstage/src/node_modules/@rsc-labs/backstage-changelog-plugin-backend/src/service/router.ts:76:26)"},"request":{"method":"GET","url":"/entity/default/component/k8s-automation"},"response":{"statusCode":404}},"cause":{},"statusCode":404,"statusText":"Not Found","name":"ResponseError"}
```

Thus can we make the card or tab logic to not be displayed if it is 404ing? only if its found, we then display the content?

**Comment by radoslaw-sz** [comment]
hi @nia-potato  - thanks for the nice words!
Is it possible that: https://github.com/RSC-Labs/backstage-changelog-plugin?tab=readme-ov-file#check-if-annotations-are-ok will help you? You can make a condition to check if annotations are present to show the card.

**Comment by radoslaw-sz** [comment]
hi @nia-potato  - did you solve an issue or you still see it?

**Comment by nia-potato** [comment]
it fixed it, thanks!

**Comment by alexvoedi** [comment]
We have the same issue but cannot use `isChangelogAnnotationConfigurationOk` because we do not add any annotations to the entities. Is there any other way to check if a changelog can be found?

**Comment by anophis** [comment]
Due to another plugin we always have ANNOTATION_SOURCE_LOCATION true.

Can't see a way to use these functions in our case.

**Comment by radoslaw-sz** [comment]
hi @alexvoedi - sorry I do not know how I missed your message in this thread...
Yeah, I think it shall be possible. I mean to check if file exists, if not, throw an error and catch on the frontend. The only thing is what to do with the frontend card - it needs to be there always, but based on the error it can be shown some message/warning/error (or hidden).
What do you think?

disclaimer: I cannot make any promise that I can spend a time soon on implementation of this.
